package com.example.MarvelSuperheroSpringbootCrud.models;



import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

// to treat the class as entity
@Entity
public class Characters {
	
	// to make the id as the primary key and make it autogenerated
	@Id
	@GeneratedValue(strategy =GenerationType.AUTO )
	private int id;
	private String name;
	private String humanName;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getHumanName() {
		return humanName;
	}
	public void setHumanName(String humanName) {
		this.humanName = humanName;
	}
	
	
	
}
